### ISSUE TITLE
Error during setup of component o365

### ISSUE THREAD

**Issue by mshish** [PTST/O365Calendar-HomeAssistant#110]
Starting yesterday evening, without any changes to my config, the o365 component stopped loading. I'm not sure where to start troubleshooting. I double checked the app permissions in Azure and nothing has changed there either (error references scopes). Any ideas on where to start looking?

```
2021-04-16 08:47:55 ERROR (MainThread) [homeassistant.setup] Error during setup of component o365
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 241, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/o365/__init__.py", line 39, in setup
    validate_permissions()
  File "/config/custom_components/o365/utils.py", line 45, in validate_permissions
    permissions = json.loads(raw)["scope"]
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 14 column 2 (char 1906)
```

**Comment by mshish** [comment]
Resolving, had more time to investigate. My O365 cached credentials had a random number and extra appended to the end:
```
 } 67.899764
}
```
I removed the extra bracket and number which fixed the issue. Not sure how it got there, but all resolved.

**Comment by antoineDion** [comment]
I had the same problem, but without the number. I simply removed the extra bracket.
