### ISSUE TITLE
Unable to fetch auth token. Error: I/O must be done in the executor

### ISSUE THREAD

**Issue by Talvien** [PTST/O365Calendar-HomeAssistant#122]
I receive a warning and consecutively an error that the auth token could not be fetched. See below the error log with entries before and after.

What I did after installing:
- MS account authorized successfully via Nabu casa URL set as Internal URL.
- reinstalled and restarted component several times
- set version attribute in manifest json to 2.1.8

2021-07-12 11:42:32 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 314, in data_received
messages, upgraded, tail = self._request_parser.feed_data(data)
File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method'"
2021-07-12 11:43:38 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for o365 doing I/O at custom_components/o365/__init__.py, line 159: self.account.con.request_token(
2021-07-12 11:43:38 ERROR (MainThread) [O365.connection] Unable to fetch auth token. Error: I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/o365/__init__.py, line 159: self.account.con.request_token(
2021-07-12 11:43:38 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 314, in data_received
messages, upgraded, tail = self._request_parser.feed_data(data)
File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method'"
2021-07-12 11:43:38 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 314, in data_received
messages, upgraded, tail = self._request_parser.feed_data(data)
File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method'"

**Comment by Talvien** [comment]
This error comes additionaly:

Logger: custom_components.o365.utils
Source: custom_components/o365/utils.py:41
Integration: Office 365 Calendar (documentation)
First occurred: 12:46:02 (2 occurrences)
Last logged: 12:46:05

Could not loacte token at .O365-token-cache/o365.token
