### ISSUE TITLE
App. is not configured as a multi-tenant application

### ISSUE THREAD

**Issue by TheGreatBorg** [PTST/O365Calendar-HomeAssistant#20]
When I try to Push Link =365 account below I get the request to that my app has to be a Multi-tenant application.

![image](https://user-images.githubusercontent.com/31419036/72252822-61fb9900-3600-11ea-8dae-416fe9ba4a8c.png)

 I have made my App. multi-tenant but I still get this error:

![image](https://user-images.githubusercontent.com/31419036/72252862-7b9ce080-3600-11ea-8072-d7dc36bb9ea1.png)

But you see that my app. is now multi-tenant:

![image](https://user-images.githubusercontent.com/31419036/72252944-9ff8bd00-3600-11ea-9c45-a54373b48d0c.png)

NB: Sorry I don't know if this is a Bug - but how can I mark this as "not a Bug"?

**Comment by TheGreatBorg** [comment]
I sovled the issue by assigning Application ID URI to my App. may be documentation should include this step also:

![image](https://user-images.githubusercontent.com/31419036/72253461-e69ae700-3601-11ea-8126-99efdb43d5b7.png)

**Comment by TheGreatBorg** [comment]
Next error this and now I don't know what to do:

![image](https://user-images.githubusercontent.com/31419036/72253803-a7b96100-3602-11ea-980d-e131115d07f5.png)

**Comment by PTST** [comment]
Regarding the first error. Did you change the tenants settings in between? it usually takes a couple of minutes before the settings propagate. The Application ID URI is not required in nay way, so im guessing you just tried before the tenant settings had propagated.

Regarding the redirect uri, can you please right click on the "Link O365 account" and click copy link address and provide me with that?

I also need the redirect uri you have set up in azure..

**Comment by PTST** [comment]
I have just pushed V1.1 https://github.com/PTST/O365Calendar-HomeAssistant/releases/tag/v1.1

In this i have enabled an alternative auth flow that you can try https://github.com/PTST/O365Calendar-HomeAssistant/#alt-auth-flow

**Comment by TheGreatBorg** [comment]
Great work.. And I have removed Application ID URI (I think and hope) but when I try alternative auth flow I copy the returned URL and paste it into the Reply field and Press Submit. But then I get another configuration notification:
![image](https://user-images.githubusercontent.com/31419036/72276558-7a83a780-3630-11ea-91aa-427f4dc99b3d.png)

**Comment by PTST** [comment]
Please attach the full home assistant logs, I have an inkling what's happening, but I need the logs to confirm

**Comment by TheGreatBorg** [comment]
Full log - not showing much:
`2020-01-13 18:10:03 WARNING (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/scripts/sonos_doorbell.yaml contains duplicate key "data_template". Check lines 7 and 9.
2020-01-13 18:10:03 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for auto_backup which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2020-01-13 18:10:03 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for breaking_changes which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2020-01-13 18:10:03 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2020-01-13 18:10:09 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for fitbit which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2020-01-13 18:10:11 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for braviatv_psk which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2020-01-13 18:10:12 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for office365calendar which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2020-01-13 18:10:20 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 408, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 286, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 340, in _async_write_ha_state
    icon = self.icon
  File "/config/custom_components/fitbit/sensor.py", line 416, in icon
    battery_level = BATTERY_LEVELS[self.extra.get('battery')]
KeyError: None
2020-01-13 18:10:22 WARNING (MainThread) [hacs] Configuration option 'python_script' is deprecated and you should remove it from your configuration, HACS will know if you use 'python_script' in your Home Assistant configuration, this option will be removed in a future release.
2020-01-13 18:10:22 WARNING (MainThread) [hacs] Configuration option 'theme' is deprecated and you should remove it from your configuration, HACS will know if you use 'theme' in your Home Assistant configuration, this option will be removed in a future release.
2020-01-13 18:11:09 ERROR (SyncWorker_0) [O365.connection] Unable to fetch auth token. Error: (missing_code) Missing code parameter in response.`

**Comment by PTST** [comment]
The last line indicates that you might not have pasted the entire url or not the correct url into the text field. Please try authenticating again. Paste the returned url here if it still does not work

You probably have to restart home assistent to ensure you are using the correct Auth notification

Sorry about the duplicate notification, that's an error on my part

**Comment by TheGreatBorg** [comment]
Well now I deleted the old app and created a new - following the guide - I got to the part where I logged into my corporate account and got the acceptance page - now I try with alternative auth:

![image](https://user-images.githubusercontent.com/31419036/72279036-8887f700-3635-11ea-86b2-9c0ce13d018f.png)

**Comment by TheGreatBorg** [comment]
I'm not sure which Return URL or which part I should copy and paste in

**Comment by PTST** [comment]
Did you set the redirect uri to https://login.microsoftonline.com/common/oauth2/nativeclient ?

Also as mentioned earlier the changes takes some minutes to propagate. So please wait 5 minutes after setting the redirect uri and try again

**Comment by PTST** [comment]
> I'm not sure which Return URL or which part I should copy and paste in

After you have successfully logged in with your Microsoft account, you will get redirected to a blank web page. Here you copy the entire url from the url bar and paste it into home assistant

**Comment by TheGreatBorg** [comment]
OK I will try

**Comment by TheGreatBorg** [comment]
Well - now I get the blank page and copy and paste the whole URL and press submit but then I just get another configuration notification even though I have setup added with sensor name and calendar:

![image](https://user-images.githubusercontent.com/31419036/72280422-955a1a00-3638-11ea-938a-0e0d0b50b9c0.png)

![image](https://user-images.githubusercontent.com/31419036/72280431-9a1ece00-3638-11ea-9034-4d70972e793f.png)

**Comment by PTST** [comment]
Could you please check whether The logs still says missing code parameter in response? 
And please paste the url you received in here as well

**Comment by TheGreatBorg** [comment]
New O365 error in log:

`2020-01-13 19:06:51 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for breaking_changes which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2020-01-13 19:06:51 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2020-01-13 19:06:51 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for auto_backup which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2020-01-13 19:06:57 ERROR (SyncWorker_2) [homeassistant.components.octoprint] Endpoint: printer Failed to update OctoPrint status.   Error: 409 Client Error: CONFLICT for url: http://192.168.1.25:80/api/printer
2020-01-13 19:06:58 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for fitbit which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2020-01-13 19:07:00 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for braviatv_psk which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2020-01-13 19:07:01 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for office365calendar which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2020-01-13 19:07:09 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 408, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 286, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 340, in _async_write_ha_state
    icon = self.icon
  File "/config/custom_components/fitbit/sensor.py", line 416, in icon
    battery_level = BATTERY_LEVELS[self.extra.get('battery')]
KeyError: None
2020-01-13 19:07:09 WARNING (MainThread) [homeassistant.components.upnp] Wanted UPnP/IGD device with UDN "uuid:060b7353-fca6-4070-85f4-1fbfb9add62c" not found, aborting
2020-01-13 19:07:11 WARNING (MainThread) [hacs] Configuration option 'python_script' is deprecated and you should remove it from your configuration, HACS will know if you use 'python_script' in your Home Assistant configuration, this option will be removed in a future release.
2020-01-13 19:07:11 WARNING (MainThread) [hacs] Configuration option 'theme' is deprecated and you should remove it from your configuration, HACS will know if you use 'theme' in your Home Assistant configuration, this option will be removed in a future release.
2020-01-13 19:07:56 WARNING (MainThread) [homeassistant.helpers.entity] Update of vacuum.xiaomi_vacuum_cleaner is taking over 10 seconds
2020-01-13 19:08:35 ERROR (SyncWorker_18) [O365.connection] Unable to fetch auth token. Error: (invalid_client) AADSTS700025: Client is public so neither 'client_assertion' nor 'client_secret' should be presented.
Trace ID: feb60858-beff-481f-a571-8bbd63b79500
Correlation ID: ae41439c-ae1c-4a8c-acf7-3422251e9f35
Timestamp: 2020-01-13 18:08:35Z`

**Comment by TheGreatBorg** [comment]
https://login.microsoftonline.com/common/oauth2/nativeclient?code=OAQABAAIAAABeAFzDwllzTYGDLh_qYbH8_4Hls4vTyfD6pN4UsNduoQYvcrnX9cESjX6GW6rYzAV_AfTSGkSLJnDpFUMRb6NHeZDqhX0uqaEZKUWwHyRiNgk9Hz0TMR085cnzpETossoFiEOUnbCUcoZBTHuhH28NbQ1WSTl6prWoezADPd-5JqJNGbBJsmSX2whSlxn9V_mmkq568CKHQfMu7obneZhCjzJmPW9gnAnQiRdGl3QAIASrFE-OWyYM0FPbhedvXMEm6Bmc2QJ3iQSTqEi37VUsy5CEnuhUCIby_3UmxAIWdEsfZNQS0oJ8hW6p9IOUkbmCInZ-Evk7b69xdA7XaDMifxZE6_x7ovq63bIgaUh0vWR-hUiRZAqt8IvLA-AHGIqTAbzvq-_vFJMUrN618x7Me5ZrvXxZ3iTlFDS06j1rgkdn12qwL7TflnUtXo_tS5a-m866lMV0ThdATesiW1HTRu8UeX2SFRZKaLrBEXe-nEPl9Qh1quaZOIUZKzm6Djc8TkRLotym4aCpRpHV5aclAqHaWTdSSPzY26E-PKDkKLODaVq2qxFsXyA1IHS7C3Yy1H5h4FQhEFb8JmOy1LR-E36DYC0SXOwqHJh8PVwdwPfn3fu8r1PVPrFVirblWBqGMHUOd3Fe7CRd36txphIGhb474xBuou1-mNJ9KFof8wEYdVEvFCLotPfiBtcZNubNTpqTnUb9AZ8LGiBrabeZf69XFlwYbcuK7NIIQhuwkY5XMYQksjysTfRKtXwyJF5XwHaW7Qia34tu7x3pkayPZwpGEOmBaA69_z6rs85BoSGVvNik26QVVYWbwjjhmSeHIGLZ46xThByxwerHenPpBcAbcfhWTDboX7cKqu_x2zdhLKmTFhFchng8mSd8UVULCx4-FC8yH4VtNdFqndltIAA&state=5EtrQXfqhkuFvMKN0pQPENVDgqJMOo&session_state=b5872ae7-3309-41fa-8f7d-19447609f2d8

**Comment by PTST** [comment]
You might need to set "deafult client type" to yes in Azure, wait a couple of minutes and try again

![Screenshot_20200113-192741_Chrome](https://user-images.githubusercontent.com/17211264/72281419-cfc4b680-363a-11ea-9769-8aeaa07ebb7f.jpg)

**Comment by TheGreatBorg** [comment]
well now this:

`2020-01-13 19:08:35 ERROR (SyncWorker_18) [O365.connection] Unable to fetch auth token. Error: (invalid_client) AADSTS700025: Client is public so neither 'client_assertion' nor 'client_secret' should be presented.
Trace ID: feb60858-beff-481f-a571-8bbd63b79500
Correlation ID: ae41439c-ae1c-4a8c-acf7-3422251e9f35
Timestamp: 2020-01-13 18:08:35Z`

**Comment by PTST** [comment]
That timestamp is the same as before, did you remember to refresh the logs?

**Comment by TheGreatBorg** [comment]
Sorry - I just saw that - Here you are:

`2020-01-13 19:47:58 ERROR (SyncWorker_2) [O365.connection] Unable to fetch auth token. Error: (mismatching_state) CSRF Warning! State not equal in request and response.
2020-01-13 19:48:20 ERROR (SyncWorker_3) [O365.connection] Unable to fetch auth token. Error: (invalid_client) AADSTS700025: Client is public so neither 'client_assertion' nor 'client_secret' should be presented.
Trace ID: d1d7f293-cb8c-45cf-aa6e-93d2deb69200
Correlation ID: 43c74d6b-9c8f-4a2c-ab1f-4316eba087d3
Timestamp: 2020-01-13 18:48:20Z
2020-01-13 19:51:33 ERROR (SyncWorker_2) [O365.connection] Unable to fetch auth token. Error: (mismatching_state) CSRF Warning! State not equal in request and response.`

**Comment by PTST** [comment]
![r1h87waoznx01](https://user-images.githubusercontent.com/17211264/72283311-c76e7a80-363e-11ea-8759-886b2f5c434f.jpg)

This is probably because of the multiple notifications. Restart home assistant to ensure that only one notification exists. Then authenticate again.

**Comment by TheGreatBorg** [comment]
Cool Pic. - I will try - and thanks for the effort

**Comment by PTST** [comment]
Please let me know either way whether it works 🇩🇰

**Comment by TheGreatBorg** [comment]
Well same error and new time stamp ;-)

`2020-01-13 20:03:04 ERROR (SyncWorker_6) [O365.connection] Unable to fetch auth token. Error: (invalid_client) AADSTS700025: Client is public so neither 'client_assertion' nor 'client_secret' should be presented.
Trace ID: 2adbe62f-ed03-4578-91f6-ef1b98108f00
Correlation ID: 00eb0173-8efa-4d12-b1bb-724c76fa76df
Timestamp: 2020-01-13 19:03:04Z`

**Comment by PTST** [comment]
Hmm... I will take a deeper look at this again tomorrow and see if I can replicate any of this myself after I fix the notification issue.

**Comment by TheGreatBorg** [comment]
OK that's fine - I expect that this is correct:
![image](https://user-images.githubusercontent.com/31419036/72284092-72336880-3640-11ea-9dd3-c7345219ea63.png)

**Comment by PTST** [comment]
![20200113_201331](https://user-images.githubusercontent.com/17211264/72284446-4795df80-3641-11ea-944b-f2a1569df4cd.jpg)

This is my setup

**Comment by TheGreatBorg** [comment]
Bingo! Thanks I'm in.

**Comment by PTST** [comment]
It does not seem to be able to find a calendar named woek_calendar. Are you sure you want to have calendar_name in your config? Calendar_name is used when you want to retrieve some other calendar than you standard one

**Comment by TheGreatBorg** [comment]
Removed names and now this:

`2020-01-13 20:49:22 WARNING (MainThread) [homeassistant.helpers.entity] Updating state for sensor.o365_calendar (<class 'custom_components.office365calendar.sensor.O365Calendar'>) took 0.539 seconds. Please report platform to the developers at https://goo.gl/Nvioub
2020-01-13 20:49:26 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 408, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 286, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 340, in _async_write_ha_state
    icon = self.icon
  File "/config/custom_components/fitbit/sensor.py", line 416, in icon`

**Comment by PTST** [comment]
I don't see any error regarding the O365 sensor? If you take a look at your entities you should have a sensor.{name variable from configuration.yaml} 
If you have removed both names then it should be sensor.o365_calendar

**Comment by PTST** [comment]
Btw did you change anything on your Azure app when you got it working?

**Comment by TheGreatBorg** [comment]
Yees I added the Redirect URI for: https://login.microsoftonline.com/common/oauth2/nativeclient

Yes I only get a warning in my Log:

`2020-01-13 21:11:05 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for office365calendar which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2020-01-13 21:11:09 WARNING (MainThread) [homeassistant.helpers.entity] Updating state for sensor.work_calendar (<class 'custom_components.office365calendar.sensor.O365Calendar'>) took 0.533 seconds. Please report platform to the developers at https://goo.gl/Nvioub`

And no sensor named "Work_calendar" exist.
![image](https://user-images.githubusercontent.com/31419036/72288624-baa35400-3649-11ea-92da-f0bc13d8cb23.png)

And if you are busy just answer me later.

**Comment by TheGreatBorg** [comment]
Well no - it's here somehow:
![image](https://user-images.githubusercontent.com/31419036/72288896-5634c480-364a-11ea-9681-9519921f2579.png)

**Comment by PTST** [comment]
Then it seems to be configured correctly and working

**Comment by TheGreatBorg** [comment]
Yep - now I just miss a calendar card to show O365 content.

**Comment by PTST** [comment]
For now i will not look into a calendar card, since i'm only personally using this sensor for automations, and my javascript is rusty enough that it would take me quite a while to create anything worthwhile

But i'm glad you got it working. I will update the readme to point out it has to be added as a web url and to not just use the checkbox for the url
