### ISSUE TITLE
Client Error: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/me/calendar | Error Message: Error authenticating with resource

### ISSUE THREAD

**Issue by febalci** [PTST/O365Calendar-HomeAssistant#27]
Getting the following error:

```
2020-01-14 15:58:13 ERROR (SyncWorker_7) [O365.connection] Client Error: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/me/calendar | Error Message: Error authenticating with resource
2020-01-14 15:58:13 ERROR (MainThread) [homeassistant.components.sensor] office365calendar: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 292, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 461, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/office365calendar/sensor.py", line 248, in update
    self._state = self.device_state_attributes["event_active"]
  File "/config/custom_components/office365calendar/sensor.py", line 142, in device_state_attributes
    calendar = schedule.get_default_calendar()
  File "/usr/local/lib/python3.7/site-packages/O365/calendar.py", line 1888, in get_default_calendar
    response = self.con.get(url)
  File "/usr/local/lib/python3.7/site-packages/O365/connection.py", line 776, in get
    return self.oauth_request(url, 'get', params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/O365/connection.py", line 765, in oauth_request
    return self._internal_request(self.session, url, method, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/O365/connection.py", line 727, in _internal_request
    raise HTTPError('{} | Error Message: {}'.format(e.args[0], error_message), response=response) from None
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/me/calendar | Error Message: Error authenticating with resource
```

Tried both with default and alt auth...

Redirect URI for default auth is:
https://XXXX.XXXX.com:8123/api/o365

Installed with HACS

**Comment by PTST** [comment]
Please upload the relevant logs from you home assistant instance

**Comment by febalci** [comment]
> 
> 
> Please upload the relevant logs from you home assistant instance

Added in the original post. Thanks...

**Comment by PTST** [comment]
Do you have the following api permissions set in you azure app?  
![2020-01-14 14_05_49-Start](https://user-images.githubusercontent.com/17211264/72346841-051ee200-36d7-11ea-8971-d8cce1c81e57.png)

At what point do you get this error? I have never seen it before. Is it before or after authenticating?

**Comment by febalci** [comment]
Yep i did them exactly the same. After restarting HA, notification comes up, i press Link O365 account; it says "you can close this screen"; and this error comes up. The only thing; in "Configured Permissions" page, it writes "Grant admin consent for XXXX COMPANY" in gray where it writes "Learn more about permissions and consent" in your screenshot. This is my work account. Do i need to contact my company admins for that?

**Comment by PTST** [comment]
Is the azure app made with your work account?

If this is the case then just make a new Azure with a private o365 account, you can still use that app to authenticate with you work account. (this is how i'm accessing my work account, without admin consent)

**Comment by febalci** [comment]
I managed to connect to my private o365 account and private calendar but private account with work calendar is not working. I understand that there is something wrong on my work account admins side. Thanks anyway...

**Comment by febalci** [comment]
UPDATE: Somehow, my last try looks succesful; i have an 0365 sensor now and no errors. Will continue to follow. Made it just like you described, azure app on private o365 account, auth on work account. Thanks...
